displayName=OSRS Bank Sync
author=kyleamielke
support=https://github.com/kyleamielke/osrs-bank-sync/issues
description=Sync your bank contents to a self-hosted endpoint (e.g. osrs-tracker)
tags=bank,sync,tracker,wealth
plugins=io.kyil.osrsbanksync.OsrsBankSyncPlugin
